---
- hosts: localhost
  connection: local
  become: true
  become_user: root
  gather_facts: no
  vars:
    git_repo: https://github.com/Bimalkhimdung/weather-app-backend-aayulogic.git
    remote_dir: /home/bimal/Devops/

  tasks:
    - name: installing required packages
      apt:
        name:
          - git
          - python3-pip
          - python3-virtualenv
        state: present

    - name: pull repo from git-repository
      git:
        repo: "{{ git_repo }}"
        dest: "{{ remote_dir }}/"
        force: yes
        update: yes

    - name: Create virtual environment
      shell: python3 -m venv {{ remote_dir }}/env

    - name: changing permission for env
      file:
        path: "{{ remote_dir }}/env/bin/activate"
        owner: bimal
        group: bimal
        mode: "0755"

    - name: activating env and installing dependencies
      block:
        - name: activating env
          shell: |
            source {{ remote_dir }}/env/bin/activate
          args:
            executable: /bin/bash
          environment:
            PATH: "{{ ansible_env.PATH }}"
        
        - name: making requirements executable
          file:
            path: "{{ remote_dir }}/requirements.txt"
            mode: u+x
        
        - name: installing dependencies
          shell: pip install -r requirements.txt
          args:
            chdir: "{{ remote_dir }}"
        
        - name: Run django Migration
          shell: |
            python3 manage.py migrate
          args:
            chdir: "{{ remote_dir }}"
        
        # Other tasks...

    - name: start gunicorn server
      shell: "{{ remote_dir }}/env/bin/gunicorn weather_app.wsgi:application --reload --bind 127.0.0.1"
