---
- hosts: 192.168.102.238
  become: true
  become_user: root
  gather_facts: no
#creating variables
  vars:
    git_repo: https://github.com/Bimalkhimdung/weather-app-backend-aayulogic.git
    remote_dir: /home/devops/Test

 #all tasks are defined here
  tasks:
   - name: installing required packages
     apt:
       name:
         - git
         - python3-pip

   - name: pull repo from git-repository
     git:
        repo: "{{ git_repo}}"
        dest: "{{ remote_dir }}/"
        force: yes
        update: yes  #This will update file if already presents
   - name: Create virtual environment
     shell: python3 -m venv {{ remote_dir }}/env

   - name: changing permission for env
     file:
       path: "{{ remote_dir }}/env/bin/activate"
       owner: devops
       group: devops
       mode: "0755"
   - name: activating env and installing dependencies
     block:   #for executing block content once
       - name: activating env
         shell: |
          source {{ remote_dir }}/env/bin/activate
         args:
           executable: /bin/bash
         environment:
           PATH: "{{ansible_env.PATH}}"

       - name: making requirements executable
         file:
           path: "{{remote_dir}}/requirements.txt"
           mode: u+x
       - name: Executing all task using loop
         shell: "{{ item }}"
         args:
           chdir: "{{ remote_dir }}"
         loop:
          - pip install -r requirements.txt
          - python3 manage.py migrate
        #- python3 manage.py feed_data_to_model
          - "{{ remote_dir }}/env/bin/gunicorn weather_app.wsgi:application --bind 192.168.102.238:8000"

