name: Ci/CD
on:
    push:
        branches: 
            - main
 
jobs:
    Deploying-and-Operating:    
        runs-on: ubuntu-latest
        timeout-minutes: 10          
        steps:
         - name: Code checkout
           uses: actions/checkout@v2
         - name: Setup SSH 
           shell: bash
           run: |

            mkdir -p /home/runner/.ssh/
            touch /home/runner/.ssh/id_rsa
            touch /home/runner/.ssh/id_rsa.pub
            touch /home/runner/.ssh/authorized_keys
            touch /home/runner/.ssh/known_hosts
            # echo -e '${{ secrets.SERVER_PRIVATE_KEY_MAIN }}' > /home/runner/.ssh/id_rsa
            # echo -e '${{ secrets.SERVER_PUBLIC_KEY_MAIN }}' > /home/runner/.ssh/id_rsa.pub
            # echo -e '${{ secrets.SERVER_PUBLIC_KEY_MAIN }}' > /home/runner/.ssh/authorized_keys
            echo -e '${{ secrets.SERVER_PRIVATE_KEY_GIT }}' > /home/runner/.ssh/id_rsa
            echo -e '${{ secrets.SERVER_PUBLIC_KEY_GIT }}' > /home/runner/.ssh/id_rsa.pub
            echo -e '${{ secrets.SERVER_PUBLIC_KEY_GIT }}' > /home/runner/.ssh/authorized_keys
            chmod 600 /home/runner/.ssh/id_rsa
            chmod 600 /home/runner/.ssh/id_rsa.pub
            service ssh status
            
            #sh-keyscan -H ${{secrets.SSH_HOST}} >> /home/runner/.ssh/known_hosts
            #ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{secrets.SSH_HOST}} >> /home/runner/.ssh/known_hosts
           
            #ssh-keyscan -H ${{ secrets.SSH_HOST}} >> /home/runner/.ssh/known_hosts
         - name: Run ansible script
           shell: bash 
           run: |
             service ssh status
             ansible-playbook -vvv --private-key /home/runner/.ssh/id_rsa -u ${{secrets.SERVER_USERNAME}} -i inventory ./Playbook/Action.yml --extra-vars " ${{secrets.SEVER_PASS}}"

#             ansible-playbook ./Playbook/Action.yml -u ${{secrets.SERVER_USERNAME}} -i ./file/inventory.yml
            



        #  - name: Running Ansible Playbook
        #    uses: dawidd6/action-ansible-playbook@v2.5.0
        #    with:
        #         playbook: ./Playbook/Action.yml
        #         directory: ./
        #         key: ${{ secrets.SERVER_PRIVATE_KEY_1 }}
        #         inventory: |
        #             [all]
        #             192.168.102.238 ansible_connection=ssh ansible_user=devops ansible_become_password=aayulogic
        #         #inventory: ${{ secrets.ANSIBLE_INVENTORY }} #ansible inventory stored in github secrets               
                
        #     #     #if: github.event.push_request.merged == 'true'
        #     # #if: github.event_name == 'push' &&  github.ref ==  'refs/heads/main' && github.event.head_commit.message == 'merge'
#eval `ssh-agent -s`
#cd ./Playbook
#ansible-playbook -vvv --private-key /home/runner/.ssh/id_rsa -u ${{secrets.SERVER_USERNAME}} -i ./file/inventory.yml ./Playbook/Action.yml
