name: ssh to remote user

on:
 push:
   branches:
     - none
 workflow_dispatch:

 

jobs:
  ssh-to-remote:
    runs-on: ubuntu-latest

    steps:
     - name: checkout code
       uses: actions/checkout@v2
    
     - name: ssh to remote
       uses: shimataro/ssh-key-action@v2
       with:
         key: ${{ secrets.SERVER_PRIVATE_KEY }}
         known_hosts: ssh-keyscan -H ${{ secrets.SSH_HOST}}{%en-draw%}
    # known_hosts: ${{ secrets.SSH.HOST }}
    
       #   run: ssh-keyscan -H ${{ secrets.SSH_HOST}}{%en-draw%} >> ~/.ssh/known_hosts
         
     - name: rinning ansible playbook
       run: |
            ansible-playbook ./Playbook/Actioin.yml 

