name: Testing for ansible code

on:
  workflow_dispatch:


jobs:
  Deplyoing_Ansible_code:
   runs-on: ubuntu-latest
   steps:
    - name: Testing code
      uses: actions/checkout@v3
    - name: installing python
      uses: actions/setup-python@v2
      with:
       python-version: 3.8
       
    - name: installing ansible
      run: |
        sudo apt update
        sudo apt install ansible -y
   
    - name: deploying Ansible code
      env:
        sec_key: ${{secret.server_key}}

      run: |
        echo "${{ sec_key }}" > ssh_key.pem
        chmod 400 ssh_key.pem
        ansible-playbook --private-key ssh_key.pem test.yml -i inventory
