name: Playbook run 
on: 
     push: 
        branches:
            - Deploy
   #workflow_dispatch:
jobs:
    Run-Ansible:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v2
            - name: steup python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - name: Install Ansible
              run: |
                  python -m pip install --upgrade pip
                  pip install ansible
            - name: Run ansible playbook
              uses:  dawidd6/action-ansible-playbook@v2
              with:
                  playbook: ./Playbook/action-test1.yml
                  directory: ./
                  key: ${{ secrets.SERVER_PUBLIC_KEY_MAIN }}
                  inventory: |
                    [all]
                    192.168.102.238 ansible_connection=ssh ansible_user=devops ansible_become_password=aayulogic
                  known_hosts: |
                    192.168.102.238