name: ssh
on:
  push:
    branches:
       - Deploy
  #workflow_dispatch:
jobs:
  ssh-to-remote:
    runs-on: ubuntu-latest

    steps:
     - name: checkout code
       uses: actions/checkout@v2
     - name: Generate SSH key pair
       run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
   
     - name: SSH into server and execute command
       run: |
        sshpass -p "$SSH_PASSWORD" ssh devopsr@192.168.102.238 "ls -la"
       env:
         SSH_PASSWORD: ${{ secrets.SEVER_PASS }}
         SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY_CUSTOM }}





