name: ssh
on:
  push:
    branches:
       - Deploy
 # workflow_dispatch:
jobs:
  ssh-to-remote:
    runs-on: ubuntu-latest

    steps:
     - name: checkout code
       uses: actions/checkout@v2
     - name: Generate SSH key pair
       run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa
        cat ~/.ssh/id_rsa.pub
        echo -e "${{ secrets.SERVER_PUBLIC_KEY_MAIN }}" > ~/.ssh/authorized_keys
        cat ~/.ssh/authorized_keys
        chmod 600 ~/.ssh/id_rsa
     - name: installing ansible
       run: |
        python -m pip install --upgrade pip
        pip install ansible

     - name: running ansible playbook
       run:
        ansible-playbook ./Playbook/action-test1.yml -i ./inventory
   
    #  - name: SSH into server and execute command
    #    run: |
    #     sshpass -p "$SSH_PASSWORD" ssh devops@192.168.102.238 "ls -la"
    #    env:
    #      SSH_PASSWORD: ${{ secrets.SEVER_PASS }}
    #      SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY_CUSTOM }}





