name: ssh
on:
  push:
    branches:
       - Deploy
  #workflow_dispatch:
jobs:
  ssh-to-remote:
    runs-on: ubuntu-latest

    steps:
     - name: checkout code
       uses: actions/checkout@v2
     - name: Generate SSH key pair
       run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
        echo "${HOME}/.ssh/id_rsa.pub" >> $GITHUB_ENV
     - name: Copy SSH public key to remote server
       run: |
         sshpass -p "${secrets.SEVER_PASS}" ssh-copy-id -i $(cat $GITHUB_ENV) devops@192.168.102.238





