on:
    push:
        branches:
            - self-hosted
jobs:
    test:
        runs-on: self-hosted
        steps:
          - name: checkout code
            uses: actions/checkout@v2
          - name: test
            run: |
                 ssh vapt.realhrsoft.com
                 pwd 
                 ls
                 ls -la
                 mkdir test
            

