on:
    push:
        branches:
            - self-hosted
jobs:
    test:
        runs-on: self-hosted
        steps:
          - name: checkout code
            uses: actions/checkout@v2
          - name: test
            run: |
                ansible-playbook ./test.yml -i inventory
            

