  name: ssh to remote user

  on:
   push:
     branches:
       - main

  jobs:
    ssh-to-remote:
      runs-on: ubuntu-latest

      steps:
       - name: checkout code
         uses: actions/checkout@v2

       - name: ssh to remote
         uses: shimataro/ssh-key-action@v2
         with:
           key: ${{ secrets.SERVER_PRIVATE_KEY }}
           known_hosts: ${{ secrets.SERVER_IP }}
           
       - name: copy with rsync
         run: rsync -n app.py ${{secrets.SERVER_USRNAME}}@${{ secrets.SERVER_IP}}:/home/devops/

