  name: ssh
  on:
     push:
       branches:
          - Deploy
    #workflow_dispatch:
  jobs:
    ssh-to-remote:
      runs-on: ubuntu-latest

      steps:
       - name: checkout code
         uses: actions/checkout@v2
       - name: ssh to remote
         uses: shimataro/ssh-key-action@v2
         with:
           key: ${{ secrets.SERVER_PRIVATE_KEY_MAIN }}
           #known_hosts: ssh-keyscan -H ${{ secrets.SSH_HOST}}{%en-draw%}
           known_hosts: unnecessary
           
       - name: Adding Known Hosts
         run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts         
       - name: copy with rsync
         run: |
             rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./app.py  devops@$192.168.102.238:/home/devops

   