  name: ssh
  on:
    push:
      branches:
         - Deploy
    #workflow_dispatch:
  jobs:
    ssh-to-remote:
      runs-on: ubuntu-latest

      steps:
       - name: checkout code
         uses: actions/checkout@v2
       - name: ssh to remote
         uses: shimataro/ssh-key-action@v2
         with:
           key: ${{ secrets.SERVER_PRIVATE_KEY_CUSTOM }}
           name: id_rsa
           #known_hosts: ssh-keyscan -H ${{ secrets.SSH_HOST}}{%en-draw%}
           known_hosts: 192.168.102.238
           if_key_exists: replace            
       - name: copy with rsync
         run: |
             rsync -avz -e ssh ./aap.py devops@$192.168.102.238: /home/devops/

   