name: SSH Connection Workflow

on:
#  push:
#   branches:
#     - Deploy
 workflow_dispatch:

jobs:
  ssh_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
              sudo apt install net-tools
              ifconfig
