name: SSH Connection Workflow

on:
#  push:
#   branches:
#     - Deploy
 workflow_dispatch:

jobs:
  ssh_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SERVER_PRIVATE_KEY_CUSTOM" > key.pem
          chmod 600 key.pem
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
  
      - name: SSH into server
        run: |
          ssh -i key.pem devops@192.168.102.238 ./Scripts/ssh.sh
  