name: SSH Connection Workflow

on:
#  push:
#   branches:
#     - Deploy
 workflow_dispatch:

jobs:
  ssh_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: actions/run-ansible-playbook@v2
        with:
          inventory: ~/inventory.ini
          playbook: ~/Playbook/gitaction.yml