name: ansible run action

on:
  push:
    branches:
      - main
jobs:
  ansible_installation:
    runs-on: ubuntu-latest

    steps:
     - name: checking code
       uses: actions/checkout@v2

     - name: installing python
       uses: actions/setup-python@v1
       with:
         python-version: "3.8"
     - name: installing ansible
       run: pip install ansible ansible-lint
     - name: clearing existing key
       run: |
          eval $( ssh-agent -s )
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          ssh-add -D
     - name: running playbook
       run: ansible-playbook ./Playbook/gitaction.yml -i inventory

            
